### ISSUE TITLE
./geonames_importer.sh: line 125: /geonames_db_struct.sql: No such file or directory [FAILED]

### ISSUE THREAD

**Issue by bporter2387** [codigofuerte/GeoNames-MySQL-DataImport#24]
./geonames_importer.sh: line 125: /geonames_db_struct.sql: No such file or directory [FAILED]

I get this error when running ./geonames_importer.sh -a create-db. To fix it, I just edit the geonames_importer.sh file and add a new line below the commented out dir name. 
# dir=$( cd "$( dirname "$0" )" && pwd )

dir=`pwd`

**Comment by thomas-boll** [comment]
Thanks for this bporter2387 ... same problem, your solution worked.

**Comment by scmoral** [comment]
Fixed in new version
